### ISSUE TITLE
Corrupt left and right plate foam dxf file?

### ISSUE THREAD

**Issue by Schweinee** [blindassassin111/SP-111_Plate_Files#2]
Im having trouble open the SP-111_Left_Plate_Foam.DXF and SP-111_Right_Plate_Foam.DXF using coreldraw 2020 and other online sources. Can anybody give me advise?

**Comment by blindassassin111** [comment]
How did you download the files? I just downloaded the full zip file for this repo and checked all files are good so might want to try downloading again?

**Comment by Schweinee** [comment]
@blindassassin111 thank you for your support, I downloaded single file and cant open it. Tried download all as zip and can open it now.
